openapi: 3.0.0
info:
  title: compagniaTrasportoAPI
  version: '1.0'
  description: È l'API SOAP offerta dalla compagnia di trasporto che racchiude la capability di prenotare un servizio di trasporto per il cliente dal suo domicilio all'aeroporto da cui parte l'aereo di suo interesse.
servers:
  - url: 'https://stoplight.io/mocks/soseng-unibo/soseng-project-documentation/7905322'
    description: testing
paths:
  /prenota:
    post:
      summary: Prenota un servizio di trasporto
      operationId: post-user
      requestBody:
        content:
          application/xml:
            schema:
              type: object
              properties:
                luoghi:
                  type: object
                  properties:
                    partenza:
                      $ref: '#/components/schemas/luogo'
                    arrivo:
                      $ref: '#/components/schemas/luogo'
                data:
                  $ref: '#/components/schemas/data'
                orario:
                  $ref: '#/components/schemas/orario'
            examples:
              Esempio:
                value: |-
                  <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:null="null.xsd">
                     <soapenv:Header/>
                     <soapenv:Body>
                        <null:richiesta>
                           <luoghi>
                              <arrivo>
                                 <cap>86042</cap>
                                 <comune>Campomarino</comune>
                                 <civico>1</civico>
                                 <provincia>CB</provincia>
                                 <via>Via Cuoro</via>
                              </arrivo>
                              <partenza>
                                 <cap>86044</cap>
                                 <comune>Termoli</comune>
                                 <civico>4</civico>
                                 <provincia>CB</provincia>
                                 <via>Via Mascolo</via>
                              </partenza>
                           </luoghi>
                           <data>
                              <anno>2020</anno>
                              <giorno>12</giorno>
                              <mese>11</mese>
                           </data>
                           <ora>
                              <hh>12</hh>
                              <mm>30</mm>
                           </ora>
                        </null:richiesta>
                     </soapenv:Body>
                  </soapenv:Envelope>
        description: Post the necessary fields for the API to create a new user.
      description: 'È la risorsa che permette di prenotare un servizio di trasporto il cui luogo di partenza, di arrivo, data e ora sono specificati nel corpo della richiesta.'
      parameters:
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/xml
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    parameters: []
components:
  schemas:
    luogo:
      title: luogo
      type: object
      properties:
        cap:
          type: integer
        comune:
          type: string
        civico:
          type: integer
        provincia:
          type: string
        via:
          type: string
    data:
      title: data
      type: object
      properties:
        anno:
          type: integer
        mese:
          type: integer
        giorno:
          type: integer
    orario:
      title: ora
      type: object
      properties:
        ora:
          type: integer
        minuti:
          type: integer
