openapi: 3.0.0
info:
  title: servizi_bancari.v1
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /paymentdata:
    parameters: []
    post:
      summary: ''
      operationId: post-paymentdata
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                card_number:
                  type: integer
                expiration:
                  type: object
                  properties:
                    month:
                      type: integer
                    year:
                      type: integer
                CVC:
                  type: integer
                circuit:
                  type: string
                transaction:
                  type: object
                  properties:
                    id:
                      type: string
                    date:
                      type: string
            examples:
              Esempio 1:
                value:
                  card_number: 1234123412341234
                  expiration:
                    month: 11
                    year: 2024
                  CVC: 123
                  circuit: maestro
                  transaction:
                    id: abcd!12
                    date: '2020-03-05, 12:06 CET'
  /link:
    parameters: []
    get:
      summary: ''
      operationId: get-link
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  link:
                    type: string
              examples:
                example-1:
                  value:
                    link: payflight.me/123ayshgga
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      security:
        - API Key - 1: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: object
                  properties:
                    value:
                      type: number
                    currency:
                      type: string
                id_flight:
                  type: string
                  description: identificatore biglietto che poi passerà alla compagnia aerea nel notificarle il pagamento
                air_company:
                  type: string
            examples:
              example-1:
                value:
                  amount:
                    value: 100
                    currency: €
                  id_flight: abcd123
                  air_company: rayflight
        description: ''
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      x-examples:
        Alice Smith:
          id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
  securitySchemes:
    API Key - 1:
      name: abcd12!
      type: apiKey
      in: header
      description: Per permettere solo ad acmesky
