openapi: 3.0.0
info:
  title: maps
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
    description: testing
paths:
  /distance:
    post:
      summary: Calcola distanza
      operationId: post-distance
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  distance:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      required:
                        - value
                        - unit
                      properties:
                        value:
                          type: number
                        unit:
                          type: string
                          minLength: 1
                required:
                  - distance
              examples:
                risposta multipla:
                  value:
                    distance:
                      - value: 1
                        unit: km
                      - value: 23
                        unit: m
                risposta semplice:
                  value:
                    distance:
                      - value: 1
                        unit: km
        '400':
          description: Bad Request
        '403':
          description: Forbidden
      description: Ottieni la distanza tra un punto e un altro punto oppure tra un punto e una lista di punti.
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                pointA:
                  type: string
                  minLength: 1
                pointsB:
                  type: array
                  items:
                    type: string
              required:
                - pointA
                - pointsB
            examples:
              richiesta multipla:
                value:
                  pointA: 'Via del corso, 1, 12345, Roma, Italia'
                  pointsB:
                    - 'Via Garibaldi, 1, 12345, Roma'
                    - 'Via Bologna, 1, 12345, Roma'
              richiesta semplice:
                value:
                  pointA: 'Via del corso, 1, 12345, Roma, Italia'
                  pointsB:
                    - 'Via Garibaldi, 1, 12345, Roma'
          application/xhtml+xml:
            schema:
              type: object
              properties: {}
        description: 'Specifica un punto di partenza e uno di arrivo, oppure un punto di partenza e una lista di punti di arrivo'
      parameters:
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/json
          required: true
      security:
        - authorization: []
      tags:
        - Operazioni
components:
  schemas: {}
  securitySchemes:
    authorization:
      type: http
      scheme: basic
security:
  - authorization: []
tags:
  - name: Panoramica
