openapi: 3.0.0
info:
  title: fornitoreDistanzeAPI
  version: '1.0'
  description: 'È l''API RESTful offerta dal *Fornitore delle distanze geografiche* che, come suggerisce il nome, vi racchiude la capability di calcolare la distanza tra due posizioni geografiche.'
servers:
  - url: 'https://soseng-unibo.stoplight.io/mocks/soseng-unibo/soseng-project-documentation/2282674'
    description: testingServer
paths:
  /distance:
    post:
      summary: Calcola distanza geografica
      operationId: post-distance
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  distance:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      type: object
                      properties:
                        value:
                          type: number
                        unit:
                          type: string
                          minLength: 1
                      required:
                        - value
                        - unit
                required:
                  - distance
              examples:
                Esempio risposta semplice:
                  value:
                    distance:
                      - value: 1
                        unit: km
                Esempio risposta multipla:
                  value:
                    distance:
                      - value: 1
                        unit: km
                      - value: 23
                        unit: m
        '400':
          description: Bad Request
        '403':
          description: Forbidden
      description: È la risorsa che restituisce la distanza geografica tra due punti geografici oppure le distanze geografiche tra un punto e ciascun punto di una lista.
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                pointA:
                  type: string
                  description: Punto geografico di partenza
                pointsB:
                  type: array
                  description: Array di punti geografici di destinazione
                  uniqueItems: false
                  items:
                    type: string
            examples:
              Esempio richiesta semplice:
                value:
                  pointA: 'Via del corso, 1, 12345, Roma, Italia'
                  pointsB:
                    - 'Via Garibaldi, 1, 12345, Roma'
              Esempio richiesta multipla:
                value:
                  pointA: 'Via del corso, 1, 12345, Roma, Italia'
                  pointsB:
                    - 'Via Garibaldi, 1, 12345, Roma'
                    - 'Via Bologna, 1, 12345, Roma'
          application/xhtml+xml:
            schema:
              type: object
              properties: {}
        description: Specifica un punto geografico di partenza e un array di uno o più punti di arrivo.
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          required: true
          description: 'Il valore deve essere il token che il cliente ha ricevuto durante la registrazione, preceduto da `Basic`'
      security:
        - authorization: []
      tags:
        - Risorse
  /registration:
    post:
      summary: Registra un nuovo utente
      operationId: post-registration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
              examples:
                Esempio:
                  value:
                    token: bWFnZ2llOnN1bW1lcnM=
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/credentials'
            examples:
              Esempio:
                value:
                  username: Mario
                  password: Albatros12
      description: 'È la risorsa che permette ad un utente di registrarsi, dopo aver fornito la propria username e password.'
      tags:
        - Risorse
components:
  schemas:
    credentials:
      title: credentials
      type: object
      properties:
        username:
          type: string
        password:
          type: string
  securitySchemes:
    authorization:
      type: http
      scheme: basic
      description: 'Questo schema di sicurezza richiede al client che nella richiesta HTTP passi anche l''header *Authorization* con le sue credenziali, nella forma di "Basic token": lo abbiamo introdotto perché vogliamo che tale API sia fruibile solo da soggetti con cui il *Fornitore delle distanze geografiche* ha preso accordi (nel nostro caso le credenziali di accesso saranno date solo ad *ACMESky*).'
security:
  - API Key - 1: []
