openapi: 3.0.0
info:
  title: prontogram
  version: '1.0'
servers:
  - url: 'https://soseng-unibo.stoplight.io/mocks/soseng-unibo/soseng-project-documentation/6636887'
    description: testing
paths:
  /message:
    post:
      summary: ''
      operationId: post-message
      responses:
        '201':
          description: Created
        '403':
          description: Forbidden
      description: Invia un messaggio
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                token:
                  type: string
                  minLength: 1
                receiver:
                  type: string
                  minLength: 1
                body:
                  type: string
                  minLength: 1
              required:
                - token
                - receiver
                - body
            examples:
              example-1:
                value:
                  token: '1234'
                  receiver: Mario rossi
                  body: 'Nuova offerta. Codice: 1234'
        description: 'È richiesto un token di autenticazione, un destinatario e il corpo del testo'
    parameters: []
    get:
      summary: get message
      operationId: get-message
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  messageId:
                    type: array
                    items:
                      type: integer
                  sender:
                    type: string
                    nullable: true
                  body:
                    type: string
                    nullable: true
                  receiver:
                    type: string
                  date:
                    type: string
                    nullable: true
                    description: Data di invio del messaggio (giorno e ora)
              examples:
                /message?messageId=100:
                  value:
                    messageId:
                      - 100
                    sender: acmesky
                    body: 'C''è una nuova offerta, codice offerta: 1234'
                    receiver: Mario Rossi
                    date: '20/02/2021, 10:04 CET'
                /message:
                  value:
                    messageId:
                      - 100
                      - 101
                      - 102
                      - 103
                    sender: null
                    body: null
                    receiver: Mario Rossi
                    date: null
        '401':
          description: Unauthorized
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '404':
          description: Not Found
      parameters:
        - schema:
            type: string
          in: query
          name: messageId
          description: Id del messaggio da leggere
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: token di autenticazione
              required:
                - token
          application/xml:
            schema:
              type: object
              properties: {}
          multipart/form-data:
            schema:
              type: object
              properties:
                '':
                  type: string
          text/html:
            schema:
              type: object
              properties: {}
          text/plain:
            schema:
              type: object
              properties: {}
          application/EDI-X12:
            schema:
              type: object
              properties: {}
        description: È richiesto un token che viene fornito dopo un processo di autenticazione
      description: Leggi tutti gli id dei messaggi oppure solo un messaggio (fornendo un messageId)
  /token:
    post:
      summary: ''
      operationId: post-token
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  token:
                    type: string
                    minLength: 1
                  expiration-date:
                    type: string
                    minLength: 1
                required:
                  - token
                  - expiration-date
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                username:
                  minLength: 1
                  type: string
                password:
                  type: string
                  minLength: 1
              required:
                - username
                - password
          application/xml:
            schema:
              description: ''
              type: object
              properties:
                username:
                  type: string
                  minLength: 1
                password:
                  type: string
                  minLength: 1
              required:
                - username
                - password
            examples: {}
          multipart/form-data:
            schema:
              type: object
              properties: {}
        description: Invia nome utente e password
      description: Richiedi token di autenticazione
      parameters: []
components:
  schemas: {}
  securitySchemes: {}
